name: Monthly Newsletter

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight on the first day of every month
  workflow_dispatch:
    inputs:
      email:
        description: 'Email address to send the newsletter to'
        required: true
      all:
        description: 'Uses all entries in the database'
        required: false
        type: boolean
        default: false
      instance:
        description: 'hosted instance to use'
        required: false
        type: string
        default: 'https://openwallet-foundation.github.io/digital-wallet-and-agent-overviews-sig/#'
jobs:
  generate-newsletter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: viewer/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: cd viewer && npm install

      - name: Generate newsletter
        run: cd viewer && node scripts/newsletter.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MJ_APIKEY_PUBLIC: ${{ secrets.MJ_APIKEY_PUBLIC }}
          MJ_APIKEY_PRIVATE: ${{ secrets.MJ_APIKEY_PRIVATE }}
          EMAIL_RECIPIENT: ${{ github.event.inputs.email }}
          NODE_ENV: ${{ vars.NODE_ENV }}
          EMAIL_STORE: true
          LOCAL: ${{ github.event.inputs.all }}
          LOCATION: ${{ github.event.inputs.instance }}     
      
      - name: Upload newsletter artifact
        uses: actions/upload-artifact@v4
        with:
          name: newsletter
          path: viewer/newsletter.html